language: python
python: 2.7
sudo: false
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
cache:
  pip: true
  directories:
  - eggs
matrix:
  fast_finish: true
before_install:
- pip install zc.buildout
- cp test-$PLONE_VERSION.cfg buildout.cfg
install:
- buildout annotate
- buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t --layer=\!PloneAppTilesLayer
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
